### ISSUE TITLE
Add chat history

### ISSUE THREAD

**Issue by martin-kirilov** [Azure-Samples/chat-with-your-data-solution-accelerator#55]
Are you planning on adding chat history stored in CosmosDB, similarly to this solution https://github.com/microsoft/sample-app-aoai-chatGPT ?

**Comment by gmndrg** [comment]
This is not planned at this time. We'll consider addition after other planned updates. In the meantime, since this is already part of other accelerators, the code can be used to customize this one. 

This will remain a general accelerator to be adapted as possible with any other custom code needed accordingly, so it can be adapted to most use cases.

**Comment by martin-kirilov** [comment]
Thanks for the update, @gmndrg !
