### ISSUE TITLE
Add required checks to `main` branch

### ISSUE THREAD

**Issue by cecheta** [Azure-Samples/chat-with-your-data-solution-accelerator#718]
# Motivation

Add the following checks to be required when merging to the `main` branch:

- Tests
- docker-build-without-push-frontend
- docker-build-without-push-backend
- docker-build-without-push-admin

Also need to enable tests to run with the `merge_group` trigger.

# Requirements

A list of requirements to consider this feature delivered
- Add `merge_group` trigger to all workflows that run tests on PRs
- Add required checks to workflows listed above
- ...

# Tasks

_To be filled in by the engineer picking up the issue_

**Comment by ross-p-smith** [comment]
Maybe I was dreaming, but I think I saw a comment about using a matrix for 2 of those files. Can we add that in whilst you are there?

**Comment by superhindupur** [comment]
> Maybe I was dreaming, but I think I saw a comment about using a matrix for 2 of those files. Can we add that in whilst you are there?

Not dreaming @ross-p-smith :) https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/pull/710 - the comment was on here. 

@cecheta if you're looking into making it into a matrix - keep in mind that it isn't just the dockerfile that needs to be parameterized, it is also the name of the app to be used in the tags. And we don't want a cartesian product of the two arrays (since Admin.Dockerfile shouldn't be used with the tag names rag-backend or rag-webapp, only with rag-admin). Let me know if that was unclear. Thanks!

**Comment by cecheta** [comment]
The following checks are now required:

- Tests
- docker-build (rag-adminwebapp, docker/Admin.Dockerfile) / docker-build
- docker-build (rag-backend, docker/Backend.Dockerfile) / docker-build
- docker-build (rag-webapp, docker/Frontend.Dockerfile) / docker-build
