### ISSUE TITLE
Update Semantic Kernel functions to not rely on LangChain

### ISSUE THREAD

**Issue by cecheta** [Azure-Samples/chat-with-your-data-solution-accelerator#759]
Required by #320 

# Description

Replace the existing functions, which use LangChain, to use Semantic Kernel functions that do not rely on LangChain.

# Tasks

_To be filled in by the engineer picking up the subtask

- [ ] Update `QuestionAnswerTool`
- [ ] Update `TextProcessingTool`
- [ ] Update `PostPromptTool`

**Comment by gaurarpit** [comment]
anyone want to pair with me on this one?

**Comment by gaurarpit** [comment]
thank you @superhindupur for pairing.

**Comment by gaurarpit** [comment]
discussed with @cecheta and @superhindupur  and agreed on below:
* Langchain is being used in QuestionAnswerTool, TextProcessingTool, PostPromptTool as a library rather than a orchestration provider.
* therefore there is no need to update these files
* Semantic Kernel orchestration processes the entire request flow using its own kernel's functions already.
* verified by doing a debug call on the entire chat flow.
